proyecto-grupal/api/package.json
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Cart.js
proyecto-grupal/api/src/models/Category.js
proyecto-grupal/api/src/models/Order.js
proyecto-grupal/api/src/models/Product.js
proyecto-grupal/api/src/models/Review.js
proyecto-grupal/api/src/models/User.js
proyecto-grupal/api/src/routes/CategoryRoute.js
proyecto-grupal/api/src/routes/ProductRoute.js
proyecto-grupal/api/src/routes/index.js

BoilerPlate

---

proyecto-grupal/client/package.json
proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/CreateProduct.jsx
proyecto-grupal/client/src/index.js

Creé la rama "creacionProducto" donde creé el componente de creación de producto. Faltaría integrar la parte de redux con las actions correspondientes al post de un producto a la BD para poder testear correctamente la funcionalidad.

Finished product creation route, hasn't been tested yet

---

proyecto-grupal/api/index.js
proyecto-grupal/api/src/Controllers/productController.js
proyecto-grupal/api/src/Services/productoService.js
proyecto-grupal/api/src/app.js
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Category.js
proyecto-grupal/api/src/models/Product.js
proyecto-grupal/api/src/routes/ProductRoute.js

termine las rutas de los productos habria que ver si no entra en conflicto con algo de los modelos, pero lo vemos si no cambiaste algo

terminado productos rutas

---

proyecto-grupal/api/index.js
proyecto-grupal/api/package.json
proyecto-grupal/api/src/controlers/dbcharge/dbcharge.js
proyecto-grupal/api/src/controlers/dbcharge/productfix.js
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Product.js
proyecto-grupal/api/src/routes/ProductRoute.js

Implementada la carga de datos a la BD

---

proyecto-grupal/client/package.json
proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/CreateProduct/CreateProduct.jsx
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css
proyecto-grupal/client/src/index.js
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/store/index.js

Creacion del componente Home, para mostrar lista de productos y searchBar.  Modificacon de App e index para incluir la ruta del home.  Correccion de algunos otros archivos del redux y CreateProduct para poder suber el front End

Home-SearchBar-dic01

---

proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.module.css
proyecto-grupal/client/src/components/ProductDetails/ProductDetails.jsx
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js
proyecto-grupal/client/src/redux/store/index.js

Se arreglaron varios issues.
Ahora levanta el home con las card y funciona el detail

fixProduct_Detail

---

proyecto-grupal/api/src/Controllers/productController.js
proyecto-grupal/api/src/Services/categoryService.js
proyecto-grupal/api/src/Services/productoService.js
proyecto-grupal/api/src/models/Category.js

trae todos los productos asociado a la categorias, las categorias son unicas,

arreglado post y valor unico para categoria

---

proyecto-grupal/api/src/Services/productoService.js

producto puede tener muchas categorias

arreglado post

---

proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

SearchBar inicial, buscando solo en el titulo del producto

william_searchBar_inicial

---

proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Se crearon los actions y reducers: Put, Delete Category & Product.

Added some redux

---

proyecto-grupal/api/src/Controllers/userController.js
proyecto-grupal/api/src/Services/userService.js
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Order.js
proyecto-grupal/api/src/models/Product.js
proyecto-grupal/api/src/models/User.js
proyecto-grupal/api/src/routes/UserRoute.js
proyecto-grupal/api/src/routes/index.js

se modificaron modelos, relaciones y se implemento la ruta y controlador para users (basico)

User Route/Controller

---

proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Reducers/Actions carrito y arreglo de problemas

Redux Cart y Arreglos

---

proyecto-grupal/api/src/db.js
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Actions/Reducers getOrders, getOrdersDetail, putReview

Redux Orders#1

---

proyecto-grupal/api/src/Controllers/userController.js
proyecto-grupal/api/src/routes/UserRoute.js

Finalizacion Controller y Route de User

fin ruta/controller User

---

proyecto-grupal/api/package.json
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Resetea la plagina en 1 cuando se hace una busqueda.

William searc bar fix

---

proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css

Se incluye un boton para crear producto desde el home

Boton-crearproducto-en home

---

proyecto-grupal/client/src/components/ProductCard/ProductCard.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.module.css

Se agrega en la card Producto el valor del rating al lado de las estrellas para poder visualizar al ordenarlo.

ratingnumber

---

proyecto-grupal/api/package.json
proyecto-grupal/api/src/Controllers/cartController.js
proyecto-grupal/api/src/Controllers/orderController.js
proyecto-grupal/api/src/Controllers/productController.js
proyecto-grupal/api/src/Services/orderService.js
proyecto-grupal/api/src/Services/productoService.js
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Order.js
proyecto-grupal/api/src/models/OrderDetail.js

arreglado put de productos 
mas rutas de carrito

Order-detail

---

proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Se crea la action para registrar usuarios en la base de datos.

added action and redux for signNewUser(), for the sign component

---

proyecto-grupal/client/public/index.html
proyecto-grupal/client/src/components/CarouselImg/CarouselImg.jsx
proyecto-grupal/client/src/components/ProductDetails/ProductDetails.jsx
proyecto-grupal/client/src/components/ProductDetails/ProductDetails.module.css

New Detail with Carousel Bootstrap working.  Si alguno quiere modificarlo por Material UI para que quede mejor bienvenido ;)
Siéntanse libre de modificar a gusto ;)

newcarousel

---

proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Login/Login.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Login/LoginModal.jsx
proyecto-grupal/client/src/components/Login/useLogin.js
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Cristian login

---

proyecto-grupal/api/package.json
proyecto-grupal/api/src/routes/checkout.js
proyecto-grupal/api/src/routes/index.js
proyecto-grupal/client/package.json
proyecto-grupal/client/src/components/MercadoPago/MercadoPago.jsx
proyecto-grupal/client/src/components/MercadoPago/MercadoPago.module.css

Se agrega en el back ruta checkout para mercadopago y en el client el componente Mercadopago.

mercadopagocommit

---

proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Login/Login.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Login/LoginModal.css
proyecto-grupal/client/src/components/Login/LoginModal.jsx

se agregan los estilos al componente de Login

login styles and link to register added

---

proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/Login/useLogin.js
proyecto-grupal/client/src/components/Register/RegisterValidateData.js
proyecto-grupal/client/src/helpers/AdminRoute.js
proyecto-grupal/client/src/helpers/PrivateRoute.js
proyecto-grupal/client/src/redux/actions/productsActions.js

Proteje las rutas del front de usuarios no legueados y que no son admin

william-proteccionRutasFront

---

proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Login/LoginModal.jsx
proyecto-grupal/client/src/components/Login/useLogin.js

Se añade funcionalidad de logout, la cual elimina el token del usuario registrado, y se ajusta el modal login, para que se cierre tras el inicio de sesión.

Logout funtionality added to Login component

---

proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/Login/Login.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Login/LoginModal.css
proyecto-grupal/client/src/components/Login/LoginModal.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.module.css
proyecto-grupal/client/src/components/Register/Register.jsx
proyecto-grupal/client/src/components/Register/Register.module.css
proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Se reorganizo el Home, se crea el boton para el menu del usuario, se activa el navbar administrativo para dichos usuarios. se el login y logout con el store de redux

william-logout-usermenu-reorderHome

---

proyecto-grupal/api/src/Controllers/dbcharge/dbcharge.js
proyecto-grupal/api/src/Controllers/dbcharge/userfix.js
proyecto-grupal/api/src/Controllers/userController.js
proyecto-grupal/api/src/models/User.js
proyecto-grupal/api/src/routes/UserRoute.js
proyecto-grupal/client/package.json
proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/Auth0/LogIn.jsx
proyecto-grupal/client/src/components/Auth0/LogIn.module.css
proyecto-grupal/client/src/components/Auth0/LogOut.jsx
proyecto-grupal/client/src/components/Auth0/LogOut.module.css
proyecto-grupal/client/src/components/Auth0/LoginSocialValidateData.js
proyecto-grupal/client/src/components/Auth0/PostLogIn.jsx
proyecto-grupal/client/src/components/Auth0/PostLogIn.module.css
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Login/Login.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Register/Register.jsx
proyecto-grupal/client/src/index.js
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Se crea toda la utenticacion con  redes sociales a a tres de auth0, integrandola con la utenticacion de usuario y passwordo desarrollada por nosotros.  Los cambios van desde el back hasta el fron.  Se debe crear un archivo .env en el front con las keys para auth0

william-autenticacion-auth0 para redes sociales integrada con la desarrollada para user-passwd

---

proyecto-grupal/api/package.json
proyecto-grupal/api/src/Controllers/reviewController.js
proyecto-grupal/api/src/Utils/cloudinary.js
proyecto-grupal/api/src/db.js
proyecto-grupal/api/src/models/Review.js
proyecto-grupal/api/src/routes/ReviewRoute.js
proyecto-grupal/api/src/routes/index.js
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Review Backend:
- getComments
- deleteComments
- postComments (Cloudinary sin probar funcionamiento hasta tener el front)

Review backend

---

proyecto-grupal/api/src/Controllers/userController.js
proyecto-grupal/api/src/routes/UserRoute.js
proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/Profile/Profile.jsx
proyecto-grupal/client/src/components/Profile/Profile.module.css
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Crea en el Home el menu del cliente y permite ver y actualizar el profile
Se se crean rutas y controllers del back para el profile
Se crean componentes para el profil en el front
Se modifica en componente Home para incluir el menu del cliente

Crea en el Home el menu del cliente y permite ver y actualizar el profile

---

proyecto-grupal/client/src/redux/actions/productsActions.js

Se solucionó un error que romía el front

Error redux

---

proyecto-grupal/client/src/components/SearchBar/SearchBar.jsx
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Busca productos y marcas referentes a lo ingrasado en el search bar, y lo muestra para que el cliente seleccion alguna si desea.

Muestra opciones sugeridas en el search bar

---

proyecto-grupal/client/src/components/Login/Login.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/Login/LoginModal.css

se arreglan los estilos del login

fix style on login modal

---

proyecto-grupal/client/src/components/CarouselImg/CarouselImg.jsx
proyecto-grupal/client/src/components/ProductDetails/ProductDetails.jsx
proyecto-grupal/client/src/components/ProductDetails/ProductDetails.module.css

se incluyen botones add to cart y go Back y se redistrubuye al informacion del producto

mejora-product-detail - se incluyen botones add to cart y go Back y se redistrubuye al informacion del producto

---

proyecto-grupal/api/src/routes/checkout.js
proyecto-grupal/client/package.json
proyecto-grupal/client/src/components/Cart/Cart.jsx
proyecto-grupal/client/src/components/Checkout/CheckoutSuccess.jsx
proyecto-grupal/client/src/index.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js
proyecto-grupal/client/src/redux/store/index.js

Se finalizo el checkout con Mercadopago, se crea el pedido y aprueba si se realiza el pago.

checkoutfinal

---

proyecto-grupal/api/src/Controllers/nodemailerController.js
proyecto-grupal/api/src/Controllers/orderController.js
proyecto-grupal/api/src/Controllers/userController.js
proyecto-grupal/api/src/models/Order.js
proyecto-grupal/api/src/routes/OrderRoute.js
proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/NavBar/NavBar.jsx
proyecto-grupal/client/src/components/OrdersAdministration/OrderAdministration.jsx
proyecto-grupal/client/src/components/OrdersAdministration/OrderAdministration.module.css
proyecto-grupal/client/src/components/OrdersAdministration/OrderRow.jsx
proyecto-grupal/client/src/redux/actions/productsActions.js
proyecto-grupal/client/src/redux/reducer/productsReducer.js

Implementado el dashboard de ordenes y otros fix minimos

order dashboard

---

proyecto-grupal/client/src/components/Cart/Cart.jsx
proyecto-grupal/client/src/components/Cart/Cart.module.css
proyecto-grupal/client/src/components/CartProduct/CartProduct.jsx
proyecto-grupal/client/src/components/CartProduct/CartProduct.module.css
proyecto-grupal/client/src/components/Reviews/OrderList.jsx
proyecto-grupal/client/src/components/Reviews/OrderList.module.css

Mejoras en el front de los componentes My Orders y Shoping Cart

Mejoras en el front de los componentes My Orders y Shoping Cart

---

proyecto-grupal/client/src/App.js
proyecto-grupal/client/src/components/Home/Home.jsx
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/MenuBar/MenuBar.jsx
proyecto-grupal/client/src/components/MenuBar/MenuBar.module.css
proyecto-grupal/client/src/components/Pagination/Pagination.jsx
proyecto-grupal/client/src/components/Pagination/Pagination.module.css
proyecto-grupal/client/src/components/ProductCard/ProductCard.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.module.css
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css

Se hacen cambios al home y otros componentes para volverlo responsive, se crea un componente de menu

Se hacen cambios al home y otros componentes para volverlo responsive, se crea un componente de menu

---

proyecto-grupal/client/src/components/Reviews/OrderList.jsx
proyecto-grupal/client/src/components/Reviews/OrderList.module.css

Agregados estilos para cuando no hay ordenes en el componente "OrderList"

OrderList styles when "No orders"

---

proyecto-grupal/client/src/redux/actions/productsActions.js

Se corrige error en la acction getuser wishlist.  al ser ejecutada en el home sin usuario logueado

Correccion erro500-getwishlist

---

proyecto-grupal/client/src/components/Cart/Cart.module.css
proyecto-grupal/client/src/components/ModifyForm/ModifyForm.jsx
proyecto-grupal/client/src/redux/actions/productsActions.js

mas arreglos de alertas y algun estilo desfasado

alert and css

---

proyecto-grupal/client/src/components/ProductCard/ProductCard.jsx
proyecto-grupal/client/src/components/ProductCard/ProductCard.module.css

Modificado los estilos de las product cards.
Agregados íconos/botones de add to cart, add to wish list y info (details)

ProductCards styles

---

proyecto-grupal/client/src/components/Cart/Cart.jsx
proyecto-grupal/client/src/components/Cart/Cart.module.css
proyecto-grupal/client/src/components/Home/Home.module.css
proyecto-grupal/client/src/components/Login/Login.jsx
proyecto-grupal/client/src/components/MenuBar/MenuBar.jsx
proyecto-grupal/client/src/components/Register/Register.jsx
proyecto-grupal/client/src/components/Register/Register.module.css
proyecto-grupal/client/src/components/SearchBar/SearchBar.module.css

Se arreglan detalles en login.
Se mejora el comportamiento responsive de los componentes Cart, Register y Home.

Responsive desing fixed in home, cart and register
